//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank.Website
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transferencia
    {
        public int Id { get; set; }
        public string CuentaIdOrigen { get; set; }
        public string CuentaIdDestino { get; set; }
        public int Monto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Cuenta CuentaDestino { get; set; }
        public virtual Cuenta CuentaOrigen { get; set; }
    }
}
